### ISSUE TITLE
no "Extensions" in settings menu

### ISSUE THREAD

**Issue by sjoenne** [TheAppgineer/roon-extension-manager#1]
I have installed roon-extention-manager on my Ubuntu machine, followed directions here, but the extensions does not show up in settings. The service is active and running according to "systemd status roon-extension-manager.service"

Any hints?

**Comment by JanKoudijs** [comment]
Hi @sjoenne,

Is your Roon Core running on the same Ubuntu machine or somewhere else?
What do you use as a Roon Remote, PC, phone, tablet?

Can you share a screenshot of the settings menu?

**Comment by sjoenne** [comment]
> Hi @sjoenne,
> 
> Is your Roon Core running on the same Ubuntu machine or somewhere else?
> What do you use as a Roon Remote, PC, phone, tablet?
> 
> Can you share a screenshot of the settings menu?

The Roon Core is running on the same machine. I use the Roon Remote on my Android phone.

![screenshot_20181230-165927_roon](https://user-images.githubusercontent.com/27410853/50548906-b4b41e00-0c54-11e9-8796-b6cc97256d99.jpg)
![screenshot_20181230-165938_roon](https://user-images.githubusercontent.com/27410853/50548907-b4b41e00-0c54-11e9-9791-e5564efeddc0.jpg)

**Comment by sjoenne** [comment]
![roonextensionmanagerservice](https://user-images.githubusercontent.com/27410853/50548945-43289f80-0c55-11e9-9557-bd5de1bb75de.png)

**Comment by JanKoudijs** [comment]
The problem is that the Extensions tab is not available in the phone interface. You have to use a PC or tablet. You can also try to run the Roon UI via Wine, there are different posts about this in the Roon forum and there is an [install script](https://github.com/RoPieee/roon-on-wine).

**Comment by sjoenne** [comment]
ahh, I see. Thank you for your time. I'll try to find a PC running windows then ;)
