### ISSUE TITLE
[Wiki] Please update the DietPi VM download link

### ISSUE THREAD

**Issue by MichaIng** [TheAppgineer/roon-extension-manager#12]
All our images have been updated from Buster to Bullseye, the download URLs accordingly 🙂: https://github.com/TheAppgineer/roon-extension-manager/wiki/VM-Setup-Instructions

**Comment by JanKoudijs** [comment]
Thanks for the heads up. Image links for Raspberry Pi and VM are updated in Wiki.

**Comment by MichaIng** [comment]
Many thanks for the quick fix 🙂.
