### ISSUE TITLE
rem-install script never makes/finds container... (docs bug?)

### ISSUE THREAD

**Issue by mfeif** [TheAppgineer/roon-extension-manager#17]
Hello there! Thanks for doing all this work on these Roon extensions. I'm new to Roon, but pretty familiar with network audio, unix, rpi's etc. I'm trying to install your projects according to your instructions [here](https://github.com/TheAppgineer/roon-extension-manager/wiki/Installation)...

When I run the rem-setup.sh script, as my own login, as 'roon' or even as 'root', it hangs on the detecting container bits... and it doesn't appear to me that the script actually gets the container running.

The instructions don't state that a user should pull/install a container on their own. And the script doesn't ever do that; it just does this forever:

```sh
until docker container inspect $NAME > /dev/null 2>&1; do
    sleep 1s
    timeout=$((timeout-1))

    if [ $timeout -eq 0 ]; then
        echo -e $FAIL
        exit 1
    fi
done
```

**Comment by JanKoudijs** [comment]
The snippet of the script is just a wait loop, the action happens just before that in enabling and starting the service. The script executed by the service performs a `docker run` that does an implicit `docker pull` if the image is not found locally. It looks like there is some issue with the service, what output do you get if you run the command `systemctl status roon-extension-manager` after the failed install?

**Comment by JanKoudijs** [comment]
Closing this for a lack of response
