### ISSUE TITLE
Extension Manager Requires Docker

### ISSUE THREAD

**Issue by psybernoid** [TheAppgineer/roon-extension-manager#19]
As in (closed) issue #16 I'm having the exact same issue.

Instead of opening a new issue, I'll go ahead and re-open this one.
I too am having the same problem. Here's my complete docker-compose. I'm using macvlan.

`version: "3.7"
services:
  roonserver:
    image: steefdebruijn/docker-roonserver:latest
    container_name: roonserver
    hostname: roonserver
    restart: unless-stopped
    networks:
      vlan4:
        ipv4_address: 10.0.1.252
    environment:
      TZ: "Europe/London"
    volumes:
      - /share/Container-Shared/Docker/roon/app:/app
      - /share/Container-Shared/Docker/roon/data:/data
      - /share/Container-Shared/Docker/roon/backup:/backup
      - /share/Media/Music:/music:ro'

'  roon-extension-manager:
    image: theappgineer/roon-extension-manager:v1.x-standalone
    container_name: roon-extension-manager
    restart: unless-stopped
    depends_on:
      - roonserver
    group_add:
      - 0
    networks:
      vlan4:
        ipv4_address: 10.0.1.181
    environment:
      - TZ=Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker/sock
      - /share/Container-Shared/Docker/roon/extensions/extension-manager:/home/node/.rem/'
  
'networks:
  vlan4:
    driver: macvlan
    driver_opts:
      parent: eth2.4
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.254`

The group of 0 is correct:
`[locroot@quint extension-manager]$ stat -c '%g' /var/run/docker.sock
0`

And docker.sock exists in the specified location (indeed, watchtower is using it with no issues)

`[locroot@quint vlan4stack]$ cd /var/run
[locroot@quint run]$ ls d*
daemon_mgr.pid  dbus@  docker@  docker.pid  docker.sock=`

This config is from a QNAP NAS. I've tried similar on a Synology, Unraid and an Ubuntu 22.04 VM. The difference being on those configs I used host networking, not macvlan. Still had the same issue.

**Comment by Ryonez** [comment]
I've also been having this problem, been trying to figure out why for far to long...

**Comment by JanKoudijs** [comment]
I suggest to start off with the `--network host` option and all other options as listed in [the documentation](https://github.com/TheAppgineer/roon-extension-manager/wiki/Installation#docker). You can of course experiment with other network configurations but I cannot give support for them.

**Comment by Ryonez** [comment]
Guess I should open a new issue a bit later. Derped and didn't realize host wasn't being used here, I am using host. 

They did say they used host in other places troubleshooting and still have the issue though.
