### ISSUE TITLE
Why do we need to mount the docker socket?

### ISSUE THREAD

**Issue by ageisen2000** [TheAppgineer/roon-extension-manager#20]
I'm always wary of mounting the docker socket. Can you explain a bit more on why this is necessary?

Does each addon spin up its own container?

**Comment by JanKoudijs** [comment]
> Does each addon spin up its own container?
Exactly that.

When an extension is selected for installation a Docker container is created, and in order to do this the Extension Manager has to talk to the Docker daemon, hence the mounting of the socket. If you run it without the socket mounted there is nothing useful to do.
